### PR TITLE
GDCG-143: Added NEMISIS and TPS bio/logo to model for homepage

### PR DESCRIPTION
**Pull request by JosephVolosin**
This PR adds NEMISIS and TPS bio/logo fields to the homepage for the SCUP. All fields are accessible through the Wagtail admin page.

### CODE REVIEW

**Comment by JosephVolosin** [comment]
Example view:
image
(Pictures re-used and example text, just showing formatting)

**Comment by acrager** [comment]
I dont believe you used the latest in the aws lightsail to build this. I'm worried that merging it will cause conflicts.

**Comment by JosephVolosin** [comment]
> I dont believe you used the latest in the aws lightsail to build this. I'm worried that merging it will cause conflicts.

Might need to update main on here - I'll check

**Comment by JosephVolosin** [comment]
Merged in the style updates from main, here's the view now
gdc-webpage

**Comment by JosephVolosin** [comment]
> Merged in the style updates from main, here's the view now gdc-webpage

Trying again.. local storage had an old version of the style.css that wasn't being re-downloaded, cleared cache and here's the view
image

**Review by acrager — APPROVED** [review]
Good additions

**Pull request merged**
